SDK.init();

SDK.ready().then(async () => {
    console.log("Azure DevOps SDK Ready");

    const workItemService =
        await SDK.getService("ms.vss-work-web.work-item-form");

    document.getElementById("btnGenerate")
        .addEventListener("click", async () => {

            const notes = document.getElementById("notes").value;
            const mode = document.getElementById("mode").value;

            if (!notes) {
                setStatus("Please enter notes before generating.");
                return;
            }

            setStatus("Generating work item content using AI...");

            // TODO: Call Spring Boot AI backend
            // const response = await fetch(...)

            // Demo data
            document.getElementById("prevTitle").innerText =
                "AI Generated Work Item Title";

            document.getElementById("prevDesc").innerText =
                "This description was generated by AI.";

            document.getElementById("btnCreate").disabled = false;
            document.getElementById("btnCopy").disabled = false;

            setStatus("Preview generated.");
        });
});

function setStatus(message) {
    document.getElementById("status").innerText = message;
}
